SCREEN_HEIGHT, SCREEN_WIDTH = 800, 800

CAR_WIDTH = SCREEN_WIDTH * 0.2
CAR_HEIGHT = SCREEN_HEIGHT * 0.2

CAR_SPEED = 4

lanes = [SCREEN_WIDTH / 3 - 1.4 * CAR_WIDTH,
         SCREEN_WIDTH * 2 / 3 - 1.3 * CAR_WIDTH,
         SCREEN_WIDTH - 1.25 * CAR_WIDTH]
